apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onlock-api
  name: onlock-api
  namespace: onlock-test
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 5
  selector:
    matchLabels:
      app: onlock-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlock-api
    spec:
      containers:
      - image: 880382163732.dkr.ecr.us-east-1.amazonaws.com/onlock-api:tagVersion
        imagePullPolicy: IfNotPresent
        name: onlock-api
   #     ports:
    #    - containerPort: 18082
        env:
          - name: spring.profiles.active
            value: test            
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: onlock-parameters
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: onlock-parameters
                key: MYSQL_USER
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: onlock-parameters
                key: MYSQL_HOST
      restartPolicy: Always
      terminationGracePeriodSeconds: 10