version: '3.5'
services:

  dbMessageTest:  
    container_name: dbMessageTest
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: dbMessage
    ports:
      - "3306:3306"    
    networks:
      - fplusf
      
  message-app:
    container_name: message-app
    build:
      context: "./"
    depends_on:
      - dbMessageTest
    expose:
      - "8600"
    ports:
      - 8600:8600
    environment:
      spring.profiles.active: test 
    links:
      - dbMessageTest
    networks:
      - fplusf

networks:
  fplusf:
    name: fplusf-net 